/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LucideActivity: typeof import('~icons/lucide/activity')['default']
    LucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    LucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
    LucidePaperclip: typeof import('~icons/lucide/paperclip')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const LucideActivity: typeof import('~icons/lucide/activity')['default']
  const LucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
  const LucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
  const LucidePaperclip: typeof import('~icons/lucide/paperclip')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}