/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    KeyboardShortcut: typeof import('./src/components/KeyboardShortcut.vue')['default']
    ListBulkBar: typeof import('./src/components/ListBulkBar.vue')['default']
    ListFooter: typeof import('./src/components/ListFooter.vue')['default']
    ListSurface: typeof import('./src/components/ListSurface.vue')['default']
    LucideActivity: typeof import('~icons/lucide/activity')['default']
    LucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    LucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
    LucidePaperclip: typeof import('~icons/lucide/paperclip')['default']
    PageBreadcrumbs: typeof import('./src/components/PageBreadcrumbs.vue')['default']
    RailEditorDialog: typeof import('./src/components/RailEditorDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SettingsProfile: typeof import('./src/components/SettingsProfile.vue')['default']
    SettingsUsers: typeof import('./src/components/SettingsUsers.vue')['default']
  }
}

// For TSX support
declare global {
  const AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
  const AppShell: typeof import('./src/components/AppShell.vue')['default']
  const KeyboardShortcut: typeof import('./src/components/KeyboardShortcut.vue')['default']
  const ListBulkBar: typeof import('./src/components/ListBulkBar.vue')['default']
  const ListFooter: typeof import('./src/components/ListFooter.vue')['default']
  const ListSurface: typeof import('./src/components/ListSurface.vue')['default']
  const LucideActivity: typeof import('~icons/lucide/activity')['default']
  const LucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
  const LucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
  const LucidePaperclip: typeof import('~icons/lucide/paperclip')['default']
  const PageBreadcrumbs: typeof import('./src/components/PageBreadcrumbs.vue')['default']
  const RailEditorDialog: typeof import('./src/components/RailEditorDialog.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
  const SettingsProfile: typeof import('./src/components/SettingsProfile.vue')['default']
  const SettingsUsers: typeof import('./src/components/SettingsUsers.vue')['default']
}